dropbox/AffectedModuleDetector

.travis.yml, affectedmoduledetector/build.gradle, build.gradle, gradle/jacoco.gradle, sample/build.gradle, sample/buildSrc/build.gradle.kts, sample/buildSrc/src/main/kotlin/com/dropbox/sample/Dependencies.kt, sample/sample-app/build.gradle, sample/sample-app/src/main/res/layout/activity_main.xml, sample/sample-core/build.gradle, sample/sample-util/build.gradle
This pull request does a few things:
1.  Adds running the unit tests for the detector
2. Pushes coverage result to https://codecov.io/gh/dropbox/AffectedModuleDetector
3. Adds assembling of the sample apps
4. Add a buildSrc/Dependencies.kt file for reusing dependencies in the sample app
=> Update travis CI to run coverage

sample/buildSrc/build.gradle.kts
Pointing the sample at `0.1.0` would have CI run against the last release.  This will ensure it will use the latest changes in the PR and on `main`.
=> Revert change to ensure sample is run with pull requests

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt
Given the different configurations that we can run with the plugin and how they are appended to the same log file I think it can be useful to have which configuration was executed.
So if we run with `ALL_AFFECTED_PROJECTS` (default) instead of having:
```
[INFO] [amd] Using real detector
```
We'd have
```
[INFO] [amd] Using real detector with ALL_AFFECTED_PROJECTS
```
This can be useful when multiple commands are executed with different configurations set.
=> Add subset to logs

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt
Previously, we'd iteration over every project and register a task which depended on the user defined task, something like:
```
:featureA:buildTestApks -> :featureA:assembleDebugAndroidTest
:featureB:buildTestApks -> :featureB:assembleDebugAndroidTest
```
With this change, we'll register it on the root:
```
:assembleAffectedAndroidTests -> :featureA:assembleDebugAndroidTest
-> :featureB:assembleDebugAndroidTest
```
I think this was the intended approach all along and just a bug.
=> Fix task registration

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt
https://github.com/dropbox/AffectedModuleDetector/pull/39 reintroduced an error where some of the tasks weren't following the extension.  This resolves it.
=> Fix task registration in plugin

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPluginTest.kt
Adds test to validate it is applied to the correct project, the correct tasks are generated, and they have the correct dependent tasks.
=> Add unit tests for affected module detector plugin

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPluginTest.kt
The module detector was being configured mid-way through the project graph evaluation.  This caused some project relations to not be identified and projects to be missed. 
This pushes the plugins call until after the projects have been evaluated, and implements a check to ensure everything has been evaluated before proceeding.
=> Ensure calls to configure are run after all projects have been configured

README.md, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfiguration.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/CommitShaProvider.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/GitClient.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/CommitShaProvider.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/ForkCommit.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/PreviousCommit.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfigurationTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/GitClientImplTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/CommitShaProviderTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/ForkCommitTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/PreviousCommitTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/mocks/MockCommandRunner.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/mocks/MockCommitShaProvider.kt, sample/build.gradle
Addresses https://github.com/dropbox/AffectedModuleDetector/issues/4
Adds the ability to compare between the fork point of the current branch.
Added a compareFrom configuration so the user is able to enter the desired behaviour when comparing the current branch changes to either:
- Previous commit
- Fork point commit
I made a `CommitShaProvider` interface which contains a function which takes the `CommandRunner` and returns a `Sha`. I would have preferred to have the `CommitShaProvider` return a single command without the CommandRunner parameter (as suggested [here](https://github.com/dropbox/AffectedModuleDetector/issues/4#issuecomment-747047679)) but nested commands aren't supported by the `ProcessBuilder` (e.g. 
```
git merge-base $(git rev-parse --abbrev-ref HEAD) $(git show-branch -a …
```
=> Add ability to compare between fork point

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/GitClient.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/GitClientImplTest.kt
Fixes https://github.com/dropbox/AffectedModuleDetector/issues/47
If you make an uncommitted change and run the command:
```
git --no-pager diff --name-only HEAD..$sha
```
the uncommitted changes wont be displayed.
If you run the command:
```
git --no-pager diff --name-only $sha
```
the uncommitted changes will be shown.
This is because HEAD points to the last commit on the branch, therefore not considering any uncommitted changes made after that point.
=> Fix for comparing with uncommitted changes

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt
Aggregate all the necessary tasks, and skip them by using the onlyIf block. 
After `projectsEvaluate` was evaluate, the task graph could not be manipulated, effectively resulting in a no op.
=> Use onlyIf block to disable tasks

README.md
The current AndroidX project link in the README leads to a 404 because the `androidx-master-dev` branch was replaced by `androidx-main` [here](https://android.googlesource.com/platform/frameworks/support/+/c19a44147515bcc4404409e27db5de4e6e9aa73c).
This PR updates the link accordingly.
Fixes https://github.com/dropbox/AffectedModuleDetector/issues/52
=> Update dead link to AndroidX project in README

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt
The `pathsAffectedAllBuilds` will only look at unknown files to trigger the build, this changed it to look at any of the changed files. 
#64
=> Ensure pathsAffectingAllBuilds will include any changed files

.github/workflows/ci_test_and_publish.yml
Migrating our CI to Github Actions. Largely the same code as https://github.com/dropbox/Store/
Passed in my fork: https://github.com/changusmc/AffectedModuleDetector/runs/3500326313
=> Add Github Actions

tools/release/deploy_cleanup.sh
The publish step in the Github Action is already calling this script, but it doesn't exist in main yet.
=> Clean up gpg keys

README.md, sample/buildSrc/src/main/kotlin/com/dropbox/sample/tasks/AffectedTasksPlugin.kt
Fix some documentation that should have been addressed in #44 
Also noted in #95
=> Fix documentation referencing an unused configuration property

README.md
Oops, fix with correct one.
https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:maven_central
=> Fix maven repo readme typo again

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt
=> Mark all projects changed if file effecting all modules changes

README.md, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfiguration.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/GitClient.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfigurationTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/GitClientImplTest.kt
The `GitClient` has support to include uncommitted code and setting a custom top but that functionality was all hard coded. This PR adds the ability to configure those in the `AffectedModuleConfiguration`
=> Add support for toggling if uncommitted code should be included

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt, sample/buildSrc/src/main/kotlin/com/dropbox/sample/tasks/AffectedTasksPlugin.kt
Fixes https://github.com/dropbox/AffectedModuleDetector/issues/115
Sample app saw the following improvements:
16 tasks created vs 38 (-58%)
0.009s decrease in time to configure (-37.5%)
=> Task Configuration Avoidance fixes

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt
This PR has two fixes
1. We no longer capture the `project` in our `afterEvaluate` statement
2. Now if the affected module detector is not enabled, we don't check to see if the project is affected when deciding to run the task
=> Fix code to better support when running project with configuration cache

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt, gradle/wrapper/gradle-wrapper.properties, sample/gradle/wrapper/gradle-wrapper.properties
In order to call `notCompatibleWithConfigurationCache` we need to be on at least Gradle 7.4 so we updated the plugin and disabled config cache for any custom tasks made using AMD
https://github.com/dropbox/AffectedModuleDetector/issues/150
=> Upgrade Gradle Plugin so we can have knowledge of how to disable config cache

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/ToStringLogger.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AttachLogsTestRule.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/mocks/MockCommandRunner.kt
`addBuildListener` is not cacheable so we needed to switch to using a Build Service to be notified when builds are finished. We know the build is finished when `close` on the BuildService is called so we can migrate to writing out to the file there. This required a bit of a rewrite of the `ToStringLogger` to accept a provider so it can properly get that param from the BuildService
=> Make `ToStringLogger` config cacheable

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorIntegrationTest.kt
Fixes #159 
I believe this fix should handle excluded modules not being added at all to the task graph by checking the configuration before adding it
=> Excluded modules should not be added to task graph

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfiguration.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/GitClient.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/ProjectGraph.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/util/File.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/util/OsQuirks.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfigurationTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorIntegrationTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/rules/SetupAndroidProject.kt
Attempt to address #37 by adding experimental Windows support (I say _experimental_ because really what we should be doing is using an abstract file system like the one from [Okio ](https://square.github.io/okio/#file-system-examples) and write proper tests for each known target platform - Linux, Mac, Windows. However to begin with I just wanted to get something that worked on Windows.)
The main issue I noticed was that `GitClientImpl` seems to always return Unix-like line endings and path separators - `"\n"` / `"/"`. However Gradle returns the appropriate constants for the target operating system. On Windows this is `"\r\n"` / `"\"`. The AffectedModuleDetector (at its heart) compares the output from Git with the output from Gradle and compares the two to work out changes. Therefore each …
=> Experimental Windows support - take 2

README.md
Just some small tweaks as I was reading through.
=> Fix README typo's

README.md, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt
- Previously you could exclude by module name (https://github.com/dropbox/AffectedModuleDetector/pull/54)
- Now you can still exclude by module name but also exclude against module path using a regex
For a module like `:a:b:c:d`
the name is `"d"` and the path is `":a:b:c:d"`.
You could now exclude using multiple styles:
```
excludedModules = [
"d",
":a:b:c:d",
":.+:d",
]
```
(you would just use one of the 3 above strings.)
=> Allow exclude by regex

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/ProjectGraph.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt
~~Will eventually fix~~ fixes #174 ~~however for the time being this only does~~ by doing the following:
1. Cleans up the testing diagram in `AffectedModuleDetectorImplTest`
* I found it a little difficult understanding the tests and how the diagram played a part in them so have renamed File (directory) references to `d` and the Gradle project references to `p`. We could have chosen any identifier but it was a little confusing for me that they were both the same not being familiar with the Gradle test tooling.
2. Adds failing tests to highlight the issue better.
3. Strips out `".."` markers in the relative project paths so that we can directly compare the Git with Gradle.
Here's a picture of how one might set up Gradle in this weird... quixotic..... way. (Excuse the typo in the screenshot …
=> Support exotic gradle projects

affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt
These changed in #178 but due to race conditions in the merge the test began to fail
=> Fix directory names in tests

README.md
This threw me for a loop and I think it may confuse other people too
=> Make it clear that you have to runAffectedUnitTests from the sample dir

.github/workflows/ci_test_and_publish.yml, .github/workflows/sample_app.yml, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt, sample/build.gradle, sample/sample-core/build.gradle
=> Add check to see if task exists on project before adding dependency

README.md, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfiguration.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/GitClient.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/GitClientImplTest.kt
It would be useful to have the ability to configure files to be ignored by the plugin.
With this functionality, you could filter files like markdown docs so your pipelines can run faster.
=> Add the ability to configure ignoredFiles

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt
Also makes `getInstance` return `null` instead of crashing if extension isn't created yet. If wanting to crash, `getOrThrow` is the better method.
=> Move configuration to before project evaluation

affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/DependencyTracker.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt, sample/buildSrc/src/main/kotlin/com/dropbox/sample/tasks/AffectedTasksPlugin.kt
I can't find anything in the Gradle 8.10 release notes or issue tracker, but we've found that the affected module detector (both versions 0.3.1 and 0.3.0) stops working on Gradle 8.10. 
Using 0.3.1 we are seeing that no tasks will run and AMD always sees that no modules have changed. I downgraded our integration to 0.3.0 to obtain logs and work around https://github.com/dropbox/AffectedModuleDetector/issues/205, and saw that AMD is correctly identifying all the changed modules, but when it goes to identify whether those changed modules should be included in the build, it always returns `false` for every module. 
I suspected that the cause was the use of `Set<Project>` and [subsequent usage](https://github.com/dropbox/AffectedModuleDetector/blob/main/affectedmoduledetector/src/main/kotlin/c …
=> Support usage in projects using Gradle 8.10 by avoiding using Project.equals

affectedmoduledetector/build.gradle, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AttachLogsTestRule.kt
Hello 👋 I found your plugin very interesting and I want to use it in my company's project. But before this would happen, I must be sure that it is still well maintained and there would be no issues during future collaboration, like submitting bugs or accepting changes from community. So I've prepared a small contribution, I would be very happy if you accept it and prove that this plugin is still getting some love by it's creators 😉 
Changes:
- bump `com.google.truth:truth` to `1.4.2` (IntelliJ reported that the previous version had some security vulnerabilities)
- afaik no additional changes were necessary because of it
- replace `com.nhaarman:mockito-kotlin` with `org.mockito.kotlin:mockito-kotlin`
- Nhaarman's library was integrated into official Mockito organization, see …
=> Update test dependencies to newer versions

README.md, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfiguration.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfigurationTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt
When No projects are changed and no unknown files are detected the plugin builds all projects.
in some cases e.g. change in ignored files  it would be nice to be able to configure the default behaviour of Building all projects
=> Ability to configure skipping build all

README.md, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfiguration.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/CommitShaProvider.kt, affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/SpecifiedRawCommitSha.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleConfigurationTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorImplTest.kt, affectedmoduledetector/src/test/kotlin/com/dropbox/affectedmoduledetector/commitshaproviders/CommitShaProviderTest.kt
- Adds a new comparison strategy, ``, that allows clients to compare against the explicitly provided commit SHA rather than relying on the plugin's git operations for determining the desired commit
- **Motivation:** It could be the case your environment leverages [git mirroring](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository), in which case a duped repository can be out of sync with the _true_ remote, leading to inaccurate determinations of the nearest ancestor commits. It also doesn't hurt to give developers this option if they wan't a slight optimization of bypassing the work needed by the git operations.
```
affectedModuleDetector {
...
specifiedRawCommitSha = "12a9c6dba8b8dbd7b374480f38c448f24101127f"
compareFrom = …
```
=> Add support for providing a raw commit SHA to compare against as a new comparison strategy
